Ap wish
capstoneW1/site-capstone-frontend pull request #32
Opened 2022-08-01 19:01 UTC by Aligary

2022-08-01 20:05 UTC, LifeBringer requested changes
Console.log

2022-08-01 20:05 UTC, LifeBringer commented on src/components/ProductDetails/ProductDetails.jsx
> +      console.log("data in toggle", data)
Hmmm

2022-08-01 20:49 UTC, Aligary commented
console logs are removed and also did fixed CSS

2022-08-02 15:40 UTC, LifeBringer approved these changes

2022-08-02 15:41 UTC, merged